### ISSUE TITLE
Application does not correctly determine it's location

### ISSUE THREAD

**Issue by JJL772** [ACBob/pycfscape#8]
in order to use the program you need to launch it inside of the directory in which it's installed. I have a bash function setup like this:
```bash
function pycfscape() {
    /path/to/pycfscape/main.py
}
```
so that I can easily run pycfscape.
However, when I try to launch it, it crashes with `No such file or directory: ./options.toml`. you should be able to check `sys.argv[0]` to get the command used to launch this program (which will usually include an absolute path).

**Comment by ACBob** [comment]
Ah, this was an over-sight on my part. Whoops.

**Comment by ACBob** [comment]
Fixed as of commit [60137068d7f1dd5c3788be88539c8451160483d4](https://github.com/ACBob/pycfscape/commit/60137068d7f1dd5c3788be88539c8451160483d4)

**Comment by JJL772** [comment]
Thanks!
